// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Conversation struct {
	ID            int64     `db:"id"`
	MemberIdOne   string    `db:"memberIdOne"`
	MemberNameOne string    `db:"memberNameOne"`
	MemberIdTwo   string    `db:"memberIdTwo"`
	MemberNameTwo string    `db:"memberNameTwo"`
	CreatedAt     time.Time `db:"createdAt"`
}

type ConversationMessage struct {
	ID             int64          `db:"id"`
	ConversationId int64          `db:"conversationId"`
	Content        string         `db:"content"`
	FileUrl        sql.NullString `db:"fileUrl"`
	Deleted        sql.NullBool   `db:"deleted"`
	DeletedAt      sql.NullTime   `db:"deletedAt"`
	CreatedAt      time.Time      `db:"createdAt"`
	UpdatedAt      sql.NullTime   `db:"updatedAt"`
}

type Message struct {
	ID        int64          `db:"id"`
	Content   string         `db:"content"`
	FileUrl   sql.NullString `db:"fileUrl"`
	MemberId  string         `db:"memberId"`
	ChannelId string         `db:"channelId"`
	Deleted   sql.NullBool   `db:"deleted"`
	DeletedAt sql.NullTime   `db:"deletedAt"`
	CreatedAt time.Time      `db:"createdAt"`
	UpdatedAt sql.NullTime   `db:"updatedAt"`
}
