// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Conversation struct {
	ID            int64        `db:"id"`
	MemberIdOne   int64        `db:"memberIdOne"`
	MemberNameOne string       `db:"memberNameOne"`
	MemberIdTwo   int64        `db:"memberIdTwo"`
	MemberNameTwo string       `db:"memberNameTwo"`
	CreatedAt     sql.NullTime `db:"createdAt"`
}

type ConversationMessage struct {
	ID             int64          `db:"id"`
	ConversationId int64          `db:"conversationId"`
	Content        string         `db:"content"`
	FileUrl        sql.NullString `db:"fileUrl"`
	Deleted        sql.NullBool   `db:"deleted"`
	DeletedAt      sql.NullTime   `db:"deletedAt"`
	CreatedAt      sql.NullTime   `db:"createdAt"`
	UpdatedAt      sql.NullTime   `db:"updatedAt"`
}

type Message struct {
	ID        int64          `db:"id"`
	Content   string         `db:"content"`
	FileUrl   sql.NullString `db:"fileUrl"`
	MemberId  int64          `db:"memberId"`
	ChannelId int64          `db:"channelId"`
	Deleted   sql.NullBool   `db:"deleted"`
	DeletedAt sql.NullTime   `db:"deletedAt"`
	CreatedAt sql.NullTime   `db:"createdAt"`
	UpdatedAt sql.NullTime   `db:"updatedAt"`
}
